### ISSUE TITLE
Cant' Apply to Humanoid

### ISSUE THREAD

**Issue by narutouzemaki802** [PhilS94/Unity-Procedural-IK-Wall-Walking-Spider#3]
Im not not sure if it was ever intended, but are there any tips or videos on how to implement the kinematics to a humanoid. I am trying to apply walking on walls to a character in Game creator and am so close. I can get the character to gravitate towards a wall but as of now it just sort of launches in the direction of a near wall and the player control is all but lost. If you had any tips or guides on how you could implement the scripts to a humanoid model that would be amazing.

**Comment by PhilS94** [comment]
Hey there!

I guess you are referring to the "wall-walking" part of the spider. There is literally no difference for spiders or humans regarding this functionality. There are multiple ways to achieve this, but usually one creates a "fake" gravity towards the object the character is supposed to stick on while deactivating the global gravity for it (in Unity deactivate the rigidbodies useGravity boolean). The direction of this fake gravity has to be updated in real time and it is usually calculated using some sort of a raycast in the characters local negative Y axis. (My spider uses two spherecasts, one in local negative Y, and the other in in local Z, that is forwards). The raycast will return the surface normal of the point it hit, which if flipped is the fake gravity you want. Now that the character sticks to surfaces, you will also have to rotate the character such that its local Y aligns with the surface normal. It is also wise to do all this smoothly by lerping/slerping the vectors and quaternions.

If say, you only want the character to stick to e.g. planets, there is no need for ray casting as you can simple take the difference vector of the character position and the planet origin point.

Now, all this said, your character controls have to support this by being completely relative to the characters coordinate frame and never relative to the global frame (There a few exceptions but you get the point). Camera movement may also have to be adjusted depending on the use case.

In this project, just look at the Spider.cs script in FixedUpdate() to see how ground alignment works. That is literally all the functionality there is for this. In the SpiderController.cs you can see how the relative Input works. Camera movement is a little more involved in this project. Hope that helps.

Regards,
Philipp
